export const messages = {
    en: {
      Account: 'Account',
      AlreadyHaveAnAccountSignIn: 'Already have an account? Sign in',
      Authors: 'Authors',
      Book: 'Book',
      Books: 'Books',
      BookSuccessfullyUpdated: 'Book successfully updated',
      cancel: 'Cancel',
      Dashboard: 'Dashboard',
      DateOfPublish: 'Date of publish',
      DateOfReturn: 'Date of return',
      DateOfTransaction: 'Date of transaction',
      DontHaveAnAccountSignUp: 'Don\'t have an account? Sign up',
      editAddTransaction: 'Edit/Add transaction',
      editMember: 'Edit member',
      email: 'Email',
      firstName: 'First name',
      ForgotPassword: 'Forgot password?',
      fullName: 'Full name',
      home: 'Home',
      isReturned: 'Is returned',
      IWantToReceivePromotions: 'I want to receive inspiration, marketing promotions and updates via email.',
      lastName: 'Last name',
      listBooks: 'List of books',
      listMembers: 'List of members',
      listTransactions: 'List of transactions',
      loading: 'Loading...',
      Logout: 'Logout',
      Member: 'Member',
      Members: 'Members',
      MemberSuccessfullyUpdated: 'Member successfully updated',
      newMember: 'New member',
      No: 'No',
      NoPages: 'Pages',
      notFound: 'Not found',
      OopsSignIn: 'Oops! there was a problem signing you in',
      password: 'Password',
      pending: 'Pending',
      phoneNumber: 'Phone number',
      Profile: 'Profile',
      save: 'Save',
      SelectABook: 'Select a book',
      SelectAMember: 'Select a member',
      SignIn: 'Sign in',
      signUp: 'Sign up',
      SignupSuccessfulPleaseCheckYourEmail: 'Signup successful. Please check your email for a confirmation link.',
      Title: 'Title',
      total: 'Total',
      TransactionDate: 'Transaction date',
      Transactions: 'Transactions',
      TransactionSuccessfullyUpdated: 'The transaction was successfully updated',
      welcome_msg: "Welcome to my app",
      WelcomeBack: 'Welcome back',
      Yes: 'Yes',
    },
    el: {
      'Already have an account? Sign In': 'Έχετε λογαριασμό;',
      'Please enter your password and you will receive an email with a link to reset your password.': 'Παρακαλώ εισάγετε τον κωδικό σας και θα σας στείλουμε ένα email με σύνδεση για να επαναφέρετε τον κωδικό σας.',
      'Reset your password': 'Επαναφορά κωδικού',
      'SignupSuccessfulPleaseCheckYourEmail': 'Εγγραφή επιτυχής. Παρακαλώ ελέγξτε το email σας για σύνδεση επιβεβαίωσης.',
      Account: 'Λογαριασμός',
      AlreadyHaveAnAccountSignIn: 'Έχετε ήδη λογαριασμό; Συνδεθείτε',
      Authors: 'Συγγραφείς',
      Book: 'Βιβλίο',
      Books: 'Βιβλία',
      BookSuccessfullyUpdated: 'Το βιβλίο ενημερώθηκε με επιτυχία',
      cancel: 'Ακύρωση',
      Dashboard: 'Ταμπέλα',
      DateOfPublish: 'Ημερομηνία έκδοσης',
      DateOfReturn: 'Ημερομηνία επιστροφής',
      DateOfTransaction: 'Ημερομηνία δανεισμού',
      DontHaveAnAccountSignUp: 'Δεν έχετε λογαριασμό;',
      editAddTransaction: 'Επεξεργασία δανεισμού',
      editMember: 'Καρτέλα μέλους',
      email: 'Διεύθυνση Email',
      firstName: 'Όνομα',
      ForgotPassword: 'Ξεχάσατε τον κωδικό;',
      fullName: 'Ονοματεπώνυμο',
      home: 'Αρχική',
      isReturned: 'Επιστράφηκε',
      IWantToReceivePromotions: 'Θέλω να λαμβάνω ενημερώσεις, προσφορές και ενημερώσεις μέσω email.',
      lastName: 'Επώνυμο',
      listBooks: 'Λίστα βιβλίων',
      listMembers: 'Λίστα μελών',
      listTransactions: 'Λίστα δανεισμών',
      loading: 'Φόρτωση...',
      Logout: 'Αποσύνδεση',
      Member: 'Μέλος',
      Members: 'Μέλη',
      MemberSuccessfullyUpdated: 'Το μέλος ενημερώθηκε με επιτυχία',
      newMember: 'Νέο μέλος',
      No: 'Όχι',
      NoPages: 'Σελίδες',
      notFound: 'Δεν βρέθηκε',
      OopsSignIn: 'Προσπαθήστε ξανά',
      password: 'Κωδικός πρόσβασης',
      pending: 'Σε εκκρεμότητα',
      phoneNumber: 'Τηλέφωνο',
      Profile: 'Προφίλ',
      save: 'Αποθήκευση',
      SelectABook: 'Επιλέξτε βιβλίο',
      SelectAMember: 'Επιλέξτε μέλος',
      SignIn: 'Σύνδεση',
      signUp: 'Εγγραφή',
      Title: 'Τίτλος',
      total: 'Σύνολο',
      TransactionDate: 'Ημερομηνία δανεισμού',
      Transactions: 'Δανεισμοί',
      TransactionSuccessfullyUpdated: 'Ο δανεισμός ενημερώθηκε με επιτυχία',
      welcome_msg: "Καλωσορίσατε στην εφαρμογή μου",
      WelcomeBack: 'Καλώς ήρθατε',
      Yes: 'Ναι',
    }
  }